version: '3.8'

services:
  # --- Blue (Primary by default) ---
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    hostname: app_blue
    ports:
      - "8081:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_POOL=${APP_POOL_BLUE} 
      - RELEASE_ID=${RELEASE_ID_BLUE}
    networks:
      - app-network

  # --- Green (Backup by default) ---
  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    hostname: app_green
    ports:
      - "8082:${PORT}"
    environment:
      - PORT=${PORT}
      # CHANGED: Was "green", now references .env
      - APP_POOL=${APP_POOL_GREEN}
      - RELEASE_ID=${RELEASE_ID_GREEN}
    networks:
      - app-network

  # --- Nginx (Reverse Proxy) ---
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./start-nginx.sh:/start-nginx.sh:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT}
    command: ["/bin/sh", "-c", "chmod +x /start-nginx.sh && /start-nginx.sh"]
    depends_on:
      - app_blue
      - app_green
    networks:
      - app-network

networks:
  app-network:
    driver: bridge